package:
  name: constyle
  version: "{{ MY_PACKAGE_VERSION }}"

source:
  path: ".."

requirements:
  build:
    - python >=3.7
    - pip
    - poetry

  run:
    - python >=3.7
    - importlib-metadata >=4.11.0,<5.0.0a

build:
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed ."
  noarch: python
  entry_points:
    - constyle = constyle.__main__:main

about:
  home: https://github.com/abrahammurciano/python-constyle
  license: GPLv3
  summary: "A Python library to add style to your console."
  description: "A Python library to add style to your console."
  dev_url: https://github.com/abrahammurciano/python-constyle
  doc_url: https://abrahammurciano.github.io/python-constyle/constyle
