name: Document and Format
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docs_and_format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Get Poetry
        uses: abatilo/actions-poetry@v2.1.3
      - name: Install
        run: poetry install
      - name: Format code
        run: poetry run black .
      - name: Generate Documentation
        run: poetry run pdoc constyle --html -o docs/ -f -c show_source_code=False
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git status --porcelain | grep . > /dev/null; then echo "true"; else echo "false"; fi)
      - name: Create Pull Request
        if: steps.git-check.outputs.modified == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          title: Autoformat and Documentation
          commit-message: autoformatted code and generated docs
          branch: docs-and-format
          token: ${{ github.token }}
          labels: automerge,notest
