# This workflow allows you to skip tests on pull requests that don't require it
# (e.g. because actual code didn't change or if they are skipped because of a tag).

name: Dummy Tests
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Tests
        run: echo "No tests were run. Don't rely on the success of this workflow if you expect tests to run and pass."